"""logs table update

Revision ID: 7bf899e3e63f
Revises: 
Create Date: 2024-09-12 23:10:30.599428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7bf899e3e63f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cities')
    op.add_column('call_logs', sa.Column('weather_summary', sa.JSON(), nullable=True))
    op.alter_column('call_logs', 'city_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_foreign_key(None, 'call_logs', 'cities2', ['city_id'], ['city_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'call_logs', type_='foreignkey')
    op.alter_column('call_logs', 'city_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('call_logs', 'weather_summary')
    op.create_table('cities',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('lon', sa.NUMERIC(precision=10, scale=5), autoincrement=False, nullable=False),
    sa.Column('lat', sa.NUMERIC(precision=10, scale=5), autoincrement=False, nullable=False),
    sa.Column('country', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='cities_pkey')
    )
    # ### end Alembic commands ###
